### ISSUE TITLE
Locales not loading

### ISSUE THREAD

**Issue by brenwell** [rxaviers/globalize-webpack-plugin#13]
First thanks for the Lib

I am having trouble getting my locales to load, probably me just being stupid.

But perhaps you can point me in the right direction

**Webpack Config**

```coffee
    new GlobalizePlugin({
      production: false
      developmentLocale: "en"
      supportedLocales: [ "cs", "de", "en", "hu", "pl", "pt", "sk", "sv" ]
      output: "i18n/[locale].[hash].js"
    })
```

**App**

```coffee

Globalize = require( "globalize" )

glob = new Globalize('de')

options = {
  style: 'symbol'
}

formatter = glob.currencyFormatter(cc, options)

return formatter(amount)

```

Setting the locale to 'en' works but anything else I get
 **`Uncaught Error: E_MISSING_BUNDLE: {"locale":"de"}`**

Thanks

**Comment by rxaviers** [comment]
This plugin assumes you're developing in one locale only (not multiple at the same time) and it assumes that in production you'll serve the app (e.g., `app.js`) extended with the requested locale (e.g., `i18n/[locale].js`).

Having said that, I assume you are trying to use two locales on development, because you have set `"en"` as developmentLocale, but you are trying to use German `"de"` inside your app. If all you want is to have a look (during development) at how your app would look like in German, change the config temporarily. If you need that your app always displays stuff in German plus another locale you should provide the cldr yourself in your config by defining `{cldr: fn()}` that returns the data you need, note you could use the [default](https://github.com/rxaviers/globalize-webpack-plugin/blob/master/util.js#L17-L21) as baseline.

Why are you defining `Globalize('de')`?

**Comment by brenwell** [comment]
Wow, thanks for the swift reply. Ok that all makes sense.

"Why are you defining Globalize('de')?" you mean as opposed to using the global object?

Simply trying to do exactly what you guessed -  change language in development.

So now I understand the development process I was wondering about the production process. I am having the same issue as the guys from #10. However the workaround is not working so well for me. Any ideas how I can get it to build for production.

Cheers

**Comment by rxaviers** [comment]
You're welcome. I've added comments on #10, basically I need more context. I'm closing this issue then. Feel free to file new issues as suggested in #10. Thanks

**Comment by brenwell** [comment]
thank you for the help man
