### ISSUE TITLE
I18n compiled data ends up in app chunk instead of i18n chunk

### ISSUE THREAD

**Issue by rxaviers** [rxaviers/globalize-webpack-plugin#21]
Impact

On production, I18n compiled data ends up in app chunk instead of i18n chunk. Therefore: (a) chunks are incorrectly ordered: vendor, app, i18n, which leads to unavailable formatters, and (b) the English version (or whatever the default locale is) gets leaked in the app as a garbage.

How to reproduce: I'm not sure, on a project I'm working on I've observed this issue. See description below.

Description:

For some unknown reason, certain modules (in webpack terms) don't show up in any chunks (in webpack terms) on `after-optimize-chunks`. Interestingly, the same module shows up in a chunk in the previous compilation step `optimize-chunks` what suggests that some chunk optimization may be making such change. Follow the [relevant piece of code](https://github.com/rxaviers/globalize-webpack-plugin/blob/de47d5a820b9ba46ea67ddf3de77ac72c292db3e/ProductionModePlugin.js#L119-L144).

A proposed fix is to gather all modules in a step like `optimize-modules`, then on `after-optimize-chunks` use that list.

**Comment by rxaviers** [comment]
Released as patch fix v0.3.3.

**Comment by alunny** [comment]
We seem to be running into a similar problem btw, and we're on 0.3.3. Trying to isolate the cause now - we have quite a complicated setup, and removing one (seemingly unrelated) import can fix the error, as can disabling the Uglify plugin.

We haven't seen i18n compiled data chunk in the app chunk, only in subsequent chunks. So some of the data loads for, say, locale('de'), and then later the page tries to switch to locale('en'), and crashes the app.

I'll dig in and try to find a root cause this week.

**Comment by alunny** [comment]
Okay, I've figured out the bug - it's with this section of the fix:

```js
module.chunks.forEach(function(chunk) {
  module.removeChunk(chunk)
});
```

This will only ever run `Math.ceil(module.chunks.length / 2)` times, because [`removeChunk` calls `Array.prototype.splice` on the underlying array of chunks](https://github.com/webpack/webpack/blob/v1.12.15/lib/removeAndDo.js). This modifies the length of the array, causing forEach to execute only once if there are 2 chunks that import the module.

For a simple example of what's happening, try this code:

```js
let list = [1,2,3,4,5];
list.forEach((item) => {
  console.log(item);
  list.splice(list.indexOf(item), 1);
});
```

This prints `1`, `3`, and `5`, but skips `2` and `4`.

**Comment by rxaviers** [comment]
Excellent catch! Thanks
