### ISSUE TITLE
Related: babel-plugin-react-intl

### ISSUE THREAD

**Issue by necolas** [rxaviers/globalize-webpack-plugin#4]
Hey, you might also be interested in the approach react-intl is taking with a babel plugin: https://github.com/yahoo/babel-plugin-react-intl

**Comment by rxaviers** [comment]
Hi @necolas, thanks for bringing this up to my attention.

Are you suggesting the babel plugin as an alternative to globalize-webpack-plugin (for users that don't need the webpack stack and want to use babel directly); or as an alternative to [globalize-compiler](https://github.com/jquery-support/globalize-compiler), which globalize-webpack-plugin uses under the hoods?

Thanks

**Comment by necolas** [comment]
I'm not suggesting anything, you'll know better than me. Just thought I'd share it with you because you're working on all these i18n related strategies and build plugins :)

**Comment by rxaviers** [comment]
Alright. The only reason I asked was because I wanted to make sure I wasn't missing anything plus I wanted to avoid divagating in my answer to you. :)

Please, always feel free to share stuff with me. It's highly appreciated.

A babel plugin is interesting. But, it wouldn't add too much value here for some reasons: (as far as I can tell with my current knowledge :stuck_out_tongue_closed_eyes:)
- globalize-webpack-plugin works for both users:  babel users and non-babel users. Note that although react.js users using JSX use babel, some users of this plugin might not.
- globalize-webpack-plugin uses the already-parsed-by-webpack AST. So, it reuses the AST parsed by whatever our users use (babel or not). So, there would be no performance advantage using a babel plugin as far as I can tell.
- globalize-webpack-plugin does stuff beyond the scope of a babel plugin, e.g., organizing the locale chunks, which would require our users to end up defining both: a babel-plugin for globalize plus this globalize-webpack-plugin.

Having said all that, a babel plugin could still be useful for some users. There's always a use case that pops up and I haven't thought of.

I'm closing this for now, we can reopen at anytime.
