### ISSUE TITLE
Production build error: Cannot find module 'iana-tz-data'

### ISSUE THREAD

**Issue by tnightingale** [rxaviers/globalize-webpack-plugin#54]
When I run <code>npm run build</code> on the [example app](https://github.com/globalizejs/globalize/tree/master/examples/app-npm-webpack) I get the following error:
```
Module parse failed: /Users/tnightingale/workspace/affinity/cbm/globalize/examples/app-npm-webpack/app/index.js Cannot find module 'iana-tz-data'
You may need an appropriate loader to handle this file type.
```
Installing the module with <code>npm install iana-tz-data</code> resolves the issue.

**Comment by rxaviers** [comment]
Thanks for reporting... Instead of using the [example app from master](https://github.com/globalizejs/globalize/tree/master/examples/app-npm-webpack), use the one from the latest stable [v1.2.3](https://github.com/globalizejs/globalize/tree/1.2.3/examples/app-npm-webpack). OR wait until stable 1.3.0 is out 😄, which by the way will include support for [timeZone](https://github.com/globalizejs/globalize/pull/701), [formatDateToParts](https://github.com/globalizejs/globalize/pull/700), and more...

PS: If you want to check out alpha 1.3.0, check this out https://github.com/rxaviers/globalize/tree/feb82a476afcc7f7a0b2a185d96ee0341e4d9485/examples/app-npm-webpack

**Comment by tnightingale** [comment]
Oh that would make sense, sorry for the hassle, thanks!
