### ISSUE TITLE
Type Error: Cannot read property 'call' of undefined -- React-Typescript

### ISSUE THREAD

**Issue by Darth-Alex** [rxaviers/globalize-webpack-plugin#95]
I have a React Typescript project with the Following Packages installed:

  "devDependencies": {
    "awesome-typescript-loader": "^5.2.1",
    "cldr-data": "^36.0.0",
    "globalize": "^1.4.2",
    "globalize-webpack-plugin": "^3.0.0",
    "html-webpack-plugin": "^3.2.0",
    "typescript": "^3.6.4",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.9.0"
  },
  "dependencies": {
    "@types/globalize": "0.0.34",
    "@types/react": "^16.9.11",
    "@types/react-dom": "^16.9.3",
    "globalize": "^1.4.2",
    "react": "^16.11.0",
    "react-dom": "^16.11.0"
  },

I´m using this WebPack config: 
https://gist.github.com/Darth-Alex/c85f151782d0302958adc5c38b394390

if production is set to true i get the following error in the browser
<img width="952" alt="globalizeerror" src="https://user-images.githubusercontent.com/1962312/68399107-26fb6600-0176-11ea-8ad0-2518b056ebef.png">

if Production mode is false, no error occurs. Everything works!

**Comment by rxaviers** [comment]
Please, start from this example https://github.com/globalizejs/globalize/tree/master/examples/app-npm-webpack and add one by one your own configurations on top of it. When you isolate the issue, please file another ticket (or update this one that I'll reopen it). At this moment this issue is too generic. Thanks
